# Generated by Django 4.0.1 on 2022-02-16 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='domain_name',
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9\\-]+[a-z0-9]\\.[a-z]+$', message='Domain names can only use letters, numbers and hyphens (“-“). Names cannot begin or end with a hyphen. Domains cannot exceed 63 characters. Domain name can only contains at least 3 characters.')]),
        ),
    ]
