# Generated by Django 4.0.1 on 2022-02-12 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9\\-]+[a-z0-9]$', message='Domain names can only use letters, numbers and hyphens (“-“). Names cannot begin or end with a hyphen. Domains cannot exceed 63 characters. Domain name can only contains at least 3 characters.')])),
                ('domain', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('[a-z]{2,3}')])),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.site'),
        ),
    ]
